<?php

namespace App\Model\system;

use Illuminate\Database\Eloquent\Model;

class dmdvt extends Model
{
    protected $table = 'dmdvt';
    protected $fillable = [
        'id',
        'dvt',
        'madvt',
    ];
}
/* 2024.02.17 update lại bảng
truncate table dmdvt;
Insert into dmdvt (dvt,madvt) values (N'DVT12','DVT2');
Insert into dmdvt (dvt,madvt) values (N'M3','DVT4');
Insert into dmdvt (dvt,madvt) values (N'Tấn','DVT5');
Insert into dmdvt (dvt,madvt) values (N'Kg','DVT6');
Insert into dmdvt (dvt,madvt) values (N'M2','DVT12');
Insert into dmdvt (dvt,madvt) values (N'Bộ','DVT24');
Insert into dmdvt (dvt,madvt) values (N'đ/lít','DVT257');
Insert into dmdvt (dvt,madvt) values (N'đ/kg','DVT347');
Insert into dmdvt (dvt,madvt) values (N'đ/két (24 chai)','DVT357');
Insert into dmdvt (dvt,madvt) values (N'đ/thùng (24 lon)','DVT367');
Insert into dmdvt (dvt,madvt) values (N'đ/lọ 100 viên','DVT387');
Insert into dmdvt (dvt,madvt) values (N'đ/chai','DVT397');
Insert into dmdvt (dvt,madvt) values (N'đ/chiếc','DVT407');
Insert into dmdvt (dvt,madvt) values (N'đ/bao','DVT417');
Insert into dmdvt (dvt,madvt) values (N'đ/mét','DVT427');
Insert into dmdvt (dvt,madvt) values (N'đ/km','DVT457');
Insert into dmdvt (dvt,madvt) values (N'đ/USD','DVT487');
Insert into dmdvt (dvt,madvt) values (N'đ/10 bắp','DVT517');
Insert into dmdvt (dvt,madvt) values (N'đ/10 quả','DVT527');
Insert into dmdvt (dvt,madvt) values (N'đ/đôi','DVT587');
Insert into dmdvt (dvt,madvt) values (N'đ/m2','DVT597');
Insert into dmdvt (dvt,madvt) values (N'đ/m3','DVT607');
Insert into dmdvt (dvt,madvt) values (N'đ/viên','DVT617');
Insert into dmdvt (dvt,madvt) values (N'đ/công','DVT627');
Insert into dmdvt (dvt,madvt) values (N'1000 đ/chiếc','DVT647');
Insert into dmdvt (dvt,madvt) values (N'đ/hộp','DVT687');
Insert into dmdvt (dvt,madvt) values (N'đ/lần','DVT707');
Insert into dmdvt (dvt,madvt) values (N'đ/tháng','DVT717');
Insert into dmdvt (dvt,madvt) values (N'đ/10 viên','DVT737');
Insert into dmdvt (dvt,madvt) values (N'đ/lốp','DVT747');
Insert into dmdvt (dvt,madvt) values (N'đ/vé','DVT767');
Insert into dmdvt (dvt,madvt) values (N'đ/quyển','DVT777');
Insert into dmdvt (dvt,madvt) values (N'đ/tờ','DVT837');
Insert into dmdvt (dvt,madvt) values (N'đ/tấm','DVT847');
Insert into dmdvt (dvt,madvt) values (N'đ/kiểu','DVT857');
Insert into dmdvt (dvt,madvt) values (N'đ/ảnh','DVT867');
Insert into dmdvt (dvt,madvt) values (N'đ/giờ','DVT877');
Insert into dmdvt (dvt,madvt) values (N'đ/quả','DVT887');
Insert into dmdvt (dvt,madvt) values (N'đ/con','DVT897');
Insert into dmdvt (dvt,madvt) values (N'đ/bình','DVT1137');
Insert into dmdvt (dvt,madvt) values (N'USD','DVT1227');
Insert into dmdvt (dvt,madvt) values (N'đ/ha/vụ','DVT1277');
Insert into dmdvt (dvt,madvt) values (N'USD/lượt','DVT1287');
Insert into dmdvt (dvt,madvt) values (N'chiếc','DVT1288');
Insert into dmdvt (dvt,madvt) values (N'chiếc/bộ','DVT1289');
Insert into dmdvt (dvt,madvt) values (N'kg/chiếc','DVT1290');
Insert into dmdvt (dvt,madvt) values (N'kg/con','DVT1291');
Insert into dmdvt (dvt,madvt) values (N'kg/lít','DVT1292');
Insert into dmdvt (dvt,madvt) values (N'người/km2','DVT1293');
Insert into dmdvt (dvt,madvt) values (N'tạ','DVT1294');
Insert into dmdvt (dvt,madvt) values (N'can','DVT1295');
Insert into dmdvt (dvt,madvt) values (N'đ/10 bông','DVT1296');
Insert into dmdvt (dvt,madvt) values (N'đ/100 gram','DVT1297');
Insert into dmdvt (dvt,madvt) values (N'đ/100 ml','DVT1298');
Insert into dmdvt (dvt,madvt) values (N'đ/b/13 kg','DVT1300');
Insert into dmdvt (dvt,madvt) values (N'đ/bát','DVT1301');
Insert into dmdvt (dvt,madvt) values (N'đ/bó','DVT1302');
Insert into dmdvt (dvt,madvt) values (N'đ/bộ','DVT1303');
Insert into dmdvt (dvt,madvt) values (N'đ/cây','DVT1304');
Insert into dmdvt (dvt,madvt) values (N'đ/chai 750ml','DVT1305');
Insert into dmdvt (dvt,madvt) values (N'đ/chuyến','DVT1306');
Insert into dmdvt (dvt,madvt) values (N'đ/cont','DVT1307');
Insert into dmdvt (dvt,madvt) values (N'đ/cuộn','DVT1308');
Insert into dmdvt (dvt,madvt) values (N'đ/Euro','DVT1309');
Insert into dmdvt (dvt,madvt) values (N'đ/khóa','DVT1311');
Insert into dmdvt (dvt,madvt) values (N'đ/kwh','DVT1312');
Insert into dmdvt (dvt,madvt) values (N'đ/lần/chiếc','DVT1313');
Insert into dmdvt (dvt,madvt) values (N'đ/ly','DVT1314');
Insert into dmdvt (dvt,madvt) values (N'đ/năm','DVT1315');
Insert into dmdvt (dvt,madvt) values (N'đ/NDT','DVT1316');
Insert into dmdvt (dvt,madvt) values (N'đ/ngày','DVT1317');
Insert into dmdvt (dvt,madvt) values (N'đ/ngày/người','DVT1318');
Insert into dmdvt (dvt,madvt) values (N'đ/ngày-đêm','DVT1319');
Insert into dmdvt (dvt,madvt) values (N'đ/người/tháng','DVT1320');
Insert into dmdvt (dvt,madvt) values (N'đ/que','DVT1321');
Insert into dmdvt (dvt,madvt) values (N'đ/ram','DVT1322');
Insert into dmdvt (dvt,madvt) values (N'đ/suất','DVT1323');
Insert into dmdvt (dvt,madvt) values (N'đ/tập','DVT1324');
Insert into dmdvt (dvt,madvt) values (N'đ/thẻ','DVT1325');
Insert into dmdvt (dvt,madvt) values (N'đ/thiệp','DVT1326');
Insert into dmdvt (dvt,madvt) values (N'đ/thỏi','DVT1328');
Insert into dmdvt (dvt,madvt) values (N'đ/trang','DVT1329');
Insert into dmdvt (dvt,madvt) values (N'đ/vòng','DVT1330');
Insert into dmdvt (dvt,madvt) values (N'đ/xe','DVT1331');
Insert into dmdvt (dvt,madvt) values (N'đồng','DVT1332');
Insert into dmdvt (dvt,madvt) values (N'gói','DVT1333');
Insert into dmdvt (dvt,madvt) values (N'Lượt','DVT1334');
Insert into dmdvt (dvt,madvt) values (N'triệu đồng/chỉ','DVT1335');
Insert into dmdvt (dvt,madvt) values (N'Tỷ đồng','DVT1336');
Insert into dmdvt (dvt,madvt) values (N'%','DVT1337');
Insert into dmdvt (dvt,madvt) values (N'1000 đ/chỉ','DVT1398');
Insert into dmdvt (dvt,madvt) values (N'Cây','DVT1407');
Insert into dmdvt (dvt,madvt) values (N'carat','DVT1427');
Insert into dmdvt (dvt,madvt) values (N'đôi','DVT1437');
Insert into dmdvt (dvt,madvt) values (N'kg/bộ','DVT1447');
Insert into dmdvt (dvt,madvt) values (N'kg/chiếc/bộ','DVT1457');
Insert into dmdvt (dvt,madvt) values (N'kg/lít/chiếc','DVT1467');
Insert into dmdvt (dvt,madvt) values (N'kg/m','DVT1477');
Insert into dmdvt (dvt,madvt) values (N'kg/m2','DVT1487');
Insert into dmdvt (dvt,madvt) values (N'kg/m2/1000 viên','DVT1497');
Insert into dmdvt (dvt,madvt) values (N'kg/m2/chiếc','DVT1507');
Insert into dmdvt (dvt,madvt) values (N'kg/m3','DVT1527');
Insert into dmdvt (dvt,madvt) values (N'M','DVT1537');
Insert into dmdvt (dvt,madvt) values (N'm/m2','DVT1547');
Insert into dmdvt (dvt,madvt) values (N'm3/chiếc','DVT1557');
Insert into dmdvt (dvt,madvt) values (N'Bình/13Kg','DVT1567');
Insert into dmdvt (dvt,madvt) values (N'Chỉ','DVT1577');
Insert into dmdvt (dvt,madvt) values (N'USD/Tấn','DVT1607');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/lượt','DVT1617');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/Tấn','DVT1627');
Insert into dmdvt (dvt,madvt) values (N'USD/khách','DVT1637');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/khách','DVT1647');
Insert into dmdvt (dvt,madvt) values (N'Bao','DVT1667');
Insert into dmdvt (dvt,madvt) values (N'Chai','DVT1677');
Insert into dmdvt (dvt,madvt) values (N'Bình','DVT1687');
Insert into dmdvt (dvt,madvt) values (N'USD/m2/tháng','DVT1697');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/m2/tháng','DVT1707');
Insert into dmdvt (dvt,madvt) values (N'USD/máy/tháng','DVT1717');
Insert into dmdvt (dvt,madvt) values (N'USD/quầy/tháng','DVT1727');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/máy/tháng','DVT1737');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/quầy/tháng','DVT1747');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/vị trí/ tháng','DVT1757');
Insert into dmdvt (dvt,madvt) values (N'USD/ghế/tháng','DVT1767');
Insert into dmdvt (dvt,madvt) values (N'USD/vị trí/tháng','DVT1777');
Insert into dmdvt (dvt,madvt) values (N'tô, bát','DVT1787');
Insert into dmdvt (dvt,madvt) values (N'Cái','DVT1797');
Insert into dmdvt (dvt,madvt) values (N'hộp','DVT1807');
Insert into dmdvt (dvt,madvt) values (N'đ/gói','DVT1817');
Insert into dmdvt (dvt,madvt) values (N'Đồng/ lít','DVT1827');
Insert into dmdvt (dvt,madvt) values (N'đ/thùng','DVT1847');
Insert into dmdvt (dvt,madvt) values (N'đ/chỉ','DVT1967');
Insert into dmdvt (dvt,madvt) values (N'đ/khảo nghiệm','DVT1977');
Insert into dmdvt (dvt,madvt) values (N'đ/chỉ tiêu','DVT1987');
Insert into dmdvt (dvt,madvt) values (N'đ/mẫu','DVT1997');
Insert into dmdvt (dvt,madvt) values (N'đ/hệ thống','DVT2007');
Insert into dmdvt (dvt,madvt) values (N'đồng/chiếc','DVT2017');
Insert into dmdvt (dvt,madvt) values (N'đ/hộ/tháng','DVT2027');
Insert into dmdvt (dvt,madvt) values (N'đ/đơn vị/tháng','DVT2037');
Insert into dmdvt (dvt,madvt) values (N'đ/vỏ','DVT2047');
Insert into dmdvt (dvt,madvt) values (N'vé','DVT2069');
Insert into dmdvt (dvt,madvt) values (N'vỉ','DVT2070');
Insert into dmdvt (dvt,madvt) values (N'lọ/liều','DVT2071');
Insert into dmdvt (dvt,madvt) values (N'quyển','DVT2072');
Insert into dmdvt (dvt,madvt) values (N'sản phẩm','DVT2073');
Insert into dmdvt (dvt,madvt) values (N'lon','DVT2075');
Insert into dmdvt (dvt,madvt) values (N'két','DVT2077');
Insert into dmdvt (dvt,madvt) values (N'mét vuông','DVT2078');
Insert into dmdvt (dvt,madvt) values (N'tờ','DVT2079');
Insert into dmdvt (dvt,madvt) values (N'Yến','DVT2080');
Insert into dmdvt (dvt,madvt) values (N'km','DVT2081');
Insert into dmdvt (dvt,madvt) values (N'lít','DVT2083');
Insert into dmdvt (dvt,madvt) values (N'khối','DVT2084');
Insert into dmdvt (dvt,madvt) values (N'Kilogam','DVT2086');
Insert into dmdvt (dvt,madvt) values (N'mét','DVT2088');
Insert into dmdvt (dvt,madvt) values (N'inch','DVT2089');
Insert into dmdvt (dvt,madvt) values (N'viên','DVT2090');
Insert into dmdvt (dvt,madvt) values (N'thùng','DVT2093');
Insert into dmdvt (dvt,madvt) values (N'lần','DVT2094');
Insert into dmdvt (dvt,madvt) values (N'dịch vụ','DVT2095');
Insert into dmdvt (dvt,madvt) values (N'NDT','DVT2097');
Insert into dmdvt (dvt,madvt) values (N'Gam','DVT2098');
Insert into dmdvt (dvt,madvt) values (N'Tấm','DVT2099');
Insert into dmdvt (dvt,madvt) values (N'Bánh','DVT2100');
Insert into dmdvt (dvt,madvt) values (N'Ống','DVT2101');
Insert into dmdvt (dvt,madvt) values (N'Tháng','DVT2102');
Insert into dmdvt (dvt,madvt) values (N'Chậu','DVT2103');
Insert into dmdvt (dvt,madvt) values (N'Tấn/KM','DVT2104');
Insert into dmdvt (dvt,madvt) values (N'Phòng','DVT2105');
Insert into dmdvt (dvt,madvt) values (N'Thước','DVT2106');
Insert into dmdvt (dvt,madvt) values (N'Kwh','DVT2108');
Insert into dmdvt (dvt,madvt) values (N'Giờ','DVT2111');
Insert into dmdvt (dvt,madvt) values (N'Trang','DVT2112');
Insert into dmdvt (dvt,madvt) values (N'Cuộn','DVT2114');
Insert into dmdvt (dvt,madvt) values (N'Tiếng','DVT2115');
Insert into dmdvt (dvt,madvt) values (N'Ram','DVT2116');
Insert into dmdvt (dvt,madvt) values (N'Chục','DVT2117');
Insert into dmdvt (dvt,madvt) values (N'Bông','DVT2118');
Insert into dmdvt (dvt,madvt) values (N'Miếng','DVT2119');
Insert into dmdvt (dvt,madvt) values (N'Bó','DVT2120');
Insert into dmdvt (dvt,madvt) values (N'Tem','DVT2121');
Insert into dmdvt (dvt,madvt) values (N'Cốc','DVT2123');
Insert into dmdvt (dvt,madvt) values (N'Ly','DVT2124');
Insert into dmdvt (dvt,madvt) values (N'Met/Tháng','DVT2125');
Insert into dmdvt (dvt,madvt) values (N'Cặp','DVT2126');
Insert into dmdvt (dvt,madvt) values (N'Phút','DVT2128');
Insert into dmdvt (dvt,madvt) values (N'Quả','DVT2129');
Insert into dmdvt (dvt,madvt) values (N'Người','DVT2130');
Insert into dmdvt (dvt,madvt) values (N'Tập','DVT2131');
Insert into dmdvt (dvt,madvt) values (N'Con','DVT2132');
Insert into dmdvt (dvt,madvt) values (N'HK','DVT2133');
Insert into dmdvt (dvt,madvt) values (N'Số','DVT2135');
Insert into dmdvt (dvt,madvt) values (N'Nải','DVT2136');
Insert into dmdvt (dvt,madvt) values (N'Tàu lá','DVT2137');
Insert into dmdvt (dvt,madvt) values (N'Bát','DVT2138');
Insert into dmdvt (dvt,madvt) values (N'Xuất','DVT2139');
Insert into dmdvt (dvt,madvt) values (N'Xe','DVT2140');
Insert into dmdvt (dvt,madvt) values (N'EUR','DVT2141');
Insert into dmdvt (dvt,madvt) values (N'Khóa','DVT2142');
Insert into dmdvt (dvt,madvt) values (N'Áo','DVT2143');
Insert into dmdvt (dvt,madvt) values (N'Quần','DVT2144');
Insert into dmdvt (dvt,madvt) values (N'chuyến','DVT2145');
Insert into dmdvt (dvt,madvt) values (N'1000/c','DVT2146');
Insert into dmdvt (dvt,madvt) values (N'đêm','DVT2147');
Insert into dmdvt (dvt,madvt) values (N'gốc','DVT2148');
Insert into dmdvt (dvt,madvt) values (N'độ','DVT2149');
Insert into dmdvt (dvt,madvt) values (N'ngày','DVT2150');
Insert into dmdvt (dvt,madvt) values (N'suất','DVT2151');
Insert into dmdvt (dvt,madvt) values (N'lọ','DVT2152');
Insert into dmdvt (dvt,madvt) values (N'trái','DVT2153');
Insert into dmdvt (dvt,madvt) values (N'cỏi','DVT2154');
Insert into dmdvt (dvt,madvt) values (N'bịch','DVT2155');
Insert into dmdvt (dvt,madvt) values (N'100 lá','DVT2156');
Insert into dmdvt (dvt,madvt) values (N'túi','DVT2158');
Insert into dmdvt (dvt,madvt) values (N'tuyến','DVT2159');
Insert into dmdvt (dvt,madvt) values (N'xấp','DVT2160');
Insert into dmdvt (dvt,madvt) values (N'táp','DVT2161');
Insert into dmdvt (dvt,madvt) values (N'kiểu','DVT2162');
Insert into dmdvt (dvt,madvt) values (N'ch','DVT2163');
Insert into dmdvt (dvt,madvt) values (N'3','DVT2164');
Insert into dmdvt (dvt,madvt) values (N'củ','DVT2165');
Insert into dmdvt (dvt,madvt) values (N'ster','DVT2166');
Insert into dmdvt (dvt,madvt) values (N'đĩa','DVT2167');
Insert into dmdvt (dvt,madvt) values (N'm2/tháng','DVT2168');
Insert into dmdvt (dvt,madvt) values (N'lạng','DVT2169');
Insert into dmdvt (dvt,madvt) values (N'c','DVT2170');
Insert into dmdvt (dvt,madvt) values (N'cành','DVT2171');
Insert into dmdvt (dvt,madvt) values (N'công','DVT2172');
Insert into dmdvt (dvt,madvt) values (N'Viên/Hạt','DVT2173');
Insert into dmdvt (dvt,madvt) values (N'UNIT','DVT2174');
Insert into dmdvt (dvt,madvt) values (N'Tút','DVT2175');
Insert into dmdvt (dvt,madvt) values (N'Thanh/Mảnh/Miếng','DVT2176');
Insert into dmdvt (dvt,madvt) values (N'Tấn dài','DVT2177');
Insert into dmdvt (dvt,madvt) values (N'Tấn (trọng lượng khô)','DVT2178');
Insert into dmdvt (dvt,madvt) values (N'Tấn (hàm lượng KL)','DVT2179');
Insert into dmdvt (dvt,madvt) values (N'Tấn (gồm container)','DVT2180');
Insert into dmdvt (dvt,madvt) values (N'Tấn (gồm bao bì)','DVT2181');
Insert into dmdvt (dvt,madvt) values (N'Tá','DVT2182');
Insert into dmdvt (dvt,madvt) values (N'Sợi','DVT2184');
Insert into dmdvt (dvt,madvt) values (N'Rupee Ấn Độ','DVT2185');
Insert into dmdvt (dvt,madvt) values (N'Riel Cambodia','DVT2186');
Insert into dmdvt (dvt,madvt) values (N'Real Brasil','DVT2187');
Insert into dmdvt (dvt,madvt) values (N'Pao','DVT2188');
Insert into dmdvt (dvt,madvt) values (N'Nhân dân tệ','DVT2189');
Insert into dmdvt (dvt,madvt) values (N'Mili mét','DVT2190');
Insert into dmdvt (dvt,madvt) values (N'Mili lít','DVT2191');
Insert into dmdvt (dvt,madvt) values (N'Mili gram','DVT2192');
Insert into dmdvt (dvt,madvt) values (N'Mét khối','DVT2193');
Insert into dmdvt (dvt,madvt) values (N'Lon/Can','DVT2194');
Insert into dmdvt (dvt,madvt) values (N'Lô (nhiều cái)','DVT2195');
Insert into dmdvt (dvt,madvt) values (N'Liều','DVT2197');
Insert into dmdvt (dvt,madvt) values (N'LBS','DVT2198');
Insert into dmdvt (dvt,madvt) values (N'Krone Đan Mạch','DVT2199');
Insert into dmdvt (dvt,madvt) values (N'Krona Thụy Điển','DVT2200');
Insert into dmdvt (dvt,madvt) values (N'Kip Lào','DVT2202');
Insert into dmdvt (dvt,madvt) values (N'Kilogam (tr.lg khô)','DVT2203');
Insert into dmdvt (dvt,madvt) values (N'Kilogam (hàm lg KL)','DVT2204');
Insert into dmdvt (dvt,madvt) values (N'Kilogam (gồm bao bì)','DVT2205');
Insert into dmdvt (dvt,madvt) values (N'Kilô/oắt giờ','DVT2206');
Insert into dmdvt (dvt,madvt) values (N'Kiện/Hộp/Bao/Gói','DVT2207');
Insert into dmdvt (dvt,madvt) values (N'Hệ thống','DVT2208');
Insert into dmdvt (dvt,madvt) values (N'Galông ruợu','DVT2209');
Insert into dmdvt (dvt,madvt) values (N'Đơn vị','DVT2210');
Insert into dmdvt (dvt,madvt) values (N'Dollar Singapore','DVT2211');
Insert into dmdvt (dvt,madvt) values (N'Dollar Canada','DVT2212');
Insert into dmdvt (dvt,madvt) values (N'Đôi/Cặp','DVT2213');
Insert into dmdvt (dvt,madvt) values (N'dm','DVT2214');
Insert into dmdvt (dvt,madvt) values (N'Cuốn','DVT2215');
Insert into dmdvt (dvt,madvt) values (N'Cụm','DVT2216');
Insert into dmdvt (dvt,madvt) values (N'Cục','DVT2217');
Insert into dmdvt (dvt,madvt) values (N'CONTAINER','DVT2218');
Insert into dmdvt (dvt,madvt) values (N'Chai/ Lọ/ Tuýp','DVT2219');
Insert into dmdvt (dvt,madvt) values (N'Cen ti mét','DVT2220');
Insert into dmdvt (dvt,madvt) values (N'Cara','DVT2221');
Insert into dmdvt (dvt,madvt) values (N'Cái/Chiếc','DVT2222');
Insert into dmdvt (dvt,madvt) values (N'Barrel','DVT2223');
Insert into dmdvt (dvt,madvt) values (N'Baht Thái Lan','DVT2224');
Insert into dmdvt (dvt,madvt) values (N'Ao/xơ','DVT2225');
Insert into dmdvt (dvt,madvt) values (N'Air Dry Met Ton','DVT2226');
Insert into dmdvt (dvt,madvt) values (N'1000 viên','DVT2227');
Insert into dmdvt (dvt,madvt) values (N'1000 quả','DVT2228');
Insert into dmdvt (dvt,madvt) values (N'1000 kiện/hộp/bao','DVT2229');
Insert into dmdvt (dvt,madvt) values (N'1000 con','DVT2230');
Insert into dmdvt (dvt,madvt) values (N'1000 cái/chiếc','DVT2231');
Insert into dmdvt (dvt,madvt) values (N'100 chiếc','DVT2232');
Insert into dmdvt (dvt,madvt) values (N'đ/ca','DVT2233');
Insert into dmdvt (dvt,madvt) values (N'đ/m','DVT2234');
Insert into dmdvt (dvt,madvt) values (N'đ/cái','DVT2235');
Insert into dmdvt (dvt,madvt) values (N'đ/cục','DVT2236');
Insert into dmdvt (dvt,madvt) values (N'đ/ống','DVT2237');
Insert into dmdvt (dvt,madvt) values (N'đ/cây/con','DVT2238');
Insert into dmdvt (dvt,madvt) values (N'đ/tuýp','DVT2239');
Insert into dmdvt (dvt,madvt) values (N'đ/lon','DVT2240');
Insert into dmdvt (dvt,madvt) values (N'đ/cột','DVT2241');
Insert into dmdvt (dvt,madvt) values (N'Đ/tấn','DVT2639');
Insert into dmdvt (dvt,madvt) values (N'Tấn (trọng lg khô)','DVT2641');
Insert into dmdvt (dvt,madvt) values (N'Tới','DVT2643');
Insert into dmdvt (dvt,madvt) values (N'đồng/kg','DVT2644');
Insert into dmdvt (dvt,madvt) values (N'Usd/quầy/chuyến','DVT2645');
Insert into dmdvt (dvt,madvt) values (N'đồng/m3','DVT2646');
Insert into dmdvt (dvt,madvt) values (N'đồng/tấn','DVT2647');
Insert into dmdvt (dvt,madvt) values (N'đồng/hộ/ngày','DVT2648');
Insert into dmdvt (dvt,madvt) values (N'đồng/đơn','DVT2649');
Insert into dmdvt (dvt,madvt) values (N'1000 đồng/ tháng/ học sinh','DVT2650');
Insert into dmdvt (dvt,madvt) values (N'đồng/túi','DVT2651');
Insert into dmdvt (dvt,madvt) values (N'đồng/bao','DVT2652');
Insert into dmdvt (dvt,madvt) values (N'đồng/hộp','DVT2653');
Insert into dmdvt (dvt,madvt) values (N'đồng/hũ','DVT2654');
Insert into dmdvt (dvt,madvt) values (N'GROSS','DVT2671');
Insert into dmdvt (dvt,madvt) values (N'BINH','DVT2672');
Insert into dmdvt (dvt,madvt) values (N'CANH (THUC VAT)','DVT2676');
Insert into dmdvt (dvt,madvt) values (N'GRAMME','DVT2679');
Insert into dmdvt (dvt,madvt) values (N'KIEN','DVT2682');
Insert into dmdvt (dvt,madvt) values (N'TUYP','DVT2685');
Insert into dmdvt (dvt,madvt) values (N'CAY (THUC VAT)','DVT2687');
Insert into dmdvt (dvt,madvt) values (N'MANH','DVT2689');
Insert into dmdvt (dvt,madvt) values (N'CHIEC','DVT2690');
Insert into dmdvt (dvt,madvt) values (N'POUND','DVT2694');
Insert into dmdvt (dvt,madvt) values (N'CON (DONG VAT)','DVT2698');
Insert into dmdvt (dvt,madvt) values (N'THANH','DVT2699');
Insert into dmdvt (dvt,madvt) values (N'LO (CHAI)','DVT2701');
Insert into dmdvt (dvt,madvt) values (N'100 GRAMME','DVT2704');
Insert into dmdvt (dvt,madvt) values (N'1000 SAN PHAM','DVT2705');
Insert into dmdvt (dvt,madvt) values (N'100 MET','DVT2706');
Insert into dmdvt (dvt,madvt) values (N'FEET VUONG','DVT2709');
Insert into dmdvt (dvt,madvt) values (N'YARD','DVT2710');
Insert into dmdvt (dvt,madvt) values (N'TA (100 KG)','DVT2711');
Insert into dmdvt (dvt,madvt) values (N'MILIGAM','DVT2712');
Insert into dmdvt (dvt,madvt) values (N'2 CHIEC/BO','DVT2713');
Insert into dmdvt (dvt,madvt) values (N'TA (12 CAI)','DVT2718');
Insert into dmdvt (dvt,madvt) values (N'1000 CAI','DVT2719');
Insert into dmdvt (dvt,madvt) values (N'100 FT','DVT2720');
Insert into dmdvt (dvt,madvt) values (N'MILILIT(ml)','DVT2721');
Insert into dmdvt (dvt,madvt) values (N'1000 CHIEC','DVT2722');
Insert into dmdvt (dvt,madvt) values (N'mm3','DVT2724');
Insert into dmdvt (dvt,madvt) values (N'XXX','DVT2725');
Insert into dmdvt (dvt,madvt) values (N'1000 BO','DVT2726');
Insert into dmdvt (dvt,madvt) values (N'UNL','DVT2727');
Insert into dmdvt (dvt,madvt) values (N'Gam (trọng lg khô)','DVT2729');
Insert into dmdvt (dvt,madvt) values (N'UNA','DVT2731');
Insert into dmdvt (dvt,madvt) values (N'Kilogam (gồm cont.)','DVT2732');
Insert into dmdvt (dvt,madvt) values (N'100 viên/hạt','DVT2733');
Insert into dmdvt (dvt,madvt) values (N'cm2','DVT2734');
Insert into dmdvt (dvt,madvt) values (N'Nghìn','DVT2735');
Insert into dmdvt (dvt,madvt) values (N'mm2','DVT2737');
Insert into dmdvt (dvt,madvt) values (N'2 CAI/BO','DVT2738');
Insert into dmdvt (dvt,madvt) values (N'HAT','DVT2739');
Insert into dmdvt (dvt,madvt) values (N'Bản','DVT2741');
Insert into dmdvt (dvt,madvt) values (N'1000 gói','DVT2742');
Insert into dmdvt (dvt,madvt) values (N'1000 cuộn','DVT2743');
Insert into dmdvt (dvt,madvt) values (N'10 mét','DVT2744');
Insert into dmdvt (dvt,madvt) values (N'Kilo lít','DVT2745');
Insert into dmdvt (dvt,madvt) values (N'Panh','DVT2746');
Insert into dmdvt (dvt,madvt) values (N'Dollar HongKong','DVT2747');
Insert into dmdvt (dvt,madvt) values (N'Bảng','DVT2748');
Insert into dmdvt (dvt,madvt) values (N'1000 bộ/hệ thống','DVT2749');
Insert into dmdvt (dvt,madvt) values (N'10 chiếc','DVT2750');
Insert into dmdvt (dvt,madvt) values (N'Tạ (100kg)','DVT2751');
Insert into dmdvt (dvt,madvt) values (N'Yên Nhật','DVT2752');
Insert into dmdvt (dvt,madvt) values (N'Quyển/Tập','DVT2753');
Insert into dmdvt (dvt,madvt) values (N'Tấn ngắn','DVT2754');
Insert into dmdvt (dvt,madvt) values (N'1000 ống','DVT2755');
Insert into dmdvt (dvt,madvt) values (N'cm3','DVT2756');
Insert into dmdvt (dvt,madvt) values (N'Dollar Australia','DVT2757');
Insert into dmdvt (dvt,madvt) values (N'Phút vuông','DVT2758');
Insert into dmdvt (dvt,madvt) values (N'Lít Anh','DVT2759');
Insert into dmdvt (dvt,madvt) values (N'I/át','DVT2760');
Insert into dmdvt (dvt,madvt) values (N'Gam (hàm lượng KL)','DVT2761');
Insert into dmdvt (dvt,madvt) values (N'VNĐ','DVT2771');
Insert into dmdvt (dvt,madvt) values (N'Vnđ/bình','DVT2772');
Insert into dmdvt (dvt,madvt) values (N'đ/lượt','DVT2791');
Insert into dmdvt (dvt,madvt) values (N'Đồng/tín chỉ','DVT2792');
Insert into dmdvt (dvt,madvt) values (N'Vnđ/kg','DVT2811');
Insert into dmdvt (dvt,madvt) values (N'đ/liều','DVT2812');
Insert into dmdvt (dvt,madvt) values (N'đ/can','DVT2813');
Insert into dmdvt (dvt,madvt) values (N'đ/lọ','DVT2814');
Insert into dmdvt (dvt,madvt) values (N'đ/ vỉ','DVT2815');
Insert into dmdvt (dvt,madvt) values (N'đ/ vỉ 10 viên','DVT2816');
Insert into dmdvt (dvt,madvt) values (N'đ/ vỉ 8 viên','DVT2817');
Insert into dmdvt (dvt,madvt) values (N'đ/ lọ 10ml','DVT2818');
Insert into dmdvt (dvt,madvt) values (N'đ/vỉ 10 ống 2ml','DVT2819');
Insert into dmdvt (dvt,madvt) values (N'Đồng/tháng','DVT2820');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/MT','DVT2821');
Insert into dmdvt (dvt,madvt) values (N'Đồng/gói','DVT2841');
Insert into dmdvt (dvt,madvt) values (N'đồng/LO','DVT2881');
Insert into dmdvt (dvt,madvt) values (N'đồng/GOI','DVT2882');
Insert into dmdvt (dvt,madvt) values (N'đồng/CHAI','DVT2883');
Insert into dmdvt (dvt,madvt) values (N'đồng/CAN5','DVT2884');
Insert into dmdvt (dvt,madvt) values (N'đồng/VIEN','DVT2885');
Insert into dmdvt (dvt,madvt) values (N'đồng/HU','DVT2886');
Insert into dmdvt (dvt,madvt) values (N'đồng/liều','DVT2901');
Insert into dmdvt (dvt,madvt) values (N'đồng/ống','DVT2902');
Insert into dmdvt (dvt,madvt) values (N'đồng/lọ','DVT2903');
Insert into dmdvt (dvt,madvt) values (N'đồng/bình','DVT2904');
Insert into dmdvt (dvt,madvt) values (N'đồng/GRT-giờ','DVT2921');
Insert into dmdvt (dvt,madvt) values (N'đồng/container','DVT2922');
Insert into dmdvt (dvt,madvt) values (N'đồng/lượt','DVT2923');
Insert into dmdvt (dvt,madvt) values (N'đồng/GRT-ngày','DVT2924');
Insert into dmdvt (dvt,madvt) values (N'Đ/tấn-ngày','DVT2925');
Insert into dmdvt (dvt,madvt) values (N'đồng/KW','DVT2926');
Insert into dmdvt (dvt,madvt) values (N'đồng/tấn-ngày','DVT2927');
Insert into dmdvt (dvt,madvt) values (N'đồng/m2-tháng','DVT2928');
Insert into dmdvt (dvt,madvt) values (N'USD/ngày','DVT2929');
Insert into dmdvt (dvt,madvt) values (N'USD/3 ngày đầu tiên','DVT2930');
Insert into dmdvt (dvt,madvt) values (N'USD/10m/cầu/ngày','DVT2931');
Insert into dmdvt (dvt,madvt) values (N'USD/lần đóng hoặc mở hầm','DVT2932');
Insert into dmdvt (dvt,madvt) values (N'USD/cont/2 ngày đầu','DVT2933');
Insert into dmdvt (dvt,madvt) values (N'USD/chiếc','DVT2934');
Insert into dmdvt (dvt,madvt) values (N'USD/container','DVT2935');
Insert into dmdvt (dvt,madvt) values (N'USD/chiếc-ngày','DVT2936');
Insert into dmdvt (dvt,madvt) values (N'đồng/tàu-ngày','DVT2937');
Insert into dmdvt (dvt,madvt) values (N'đồng/phương tiện','DVT2938');
Insert into dmdvt (dvt,madvt) values (N'đồng/tấn phương tiện-ngày','DVT2939');
Insert into dmdvt (dvt,madvt) values (N'đồng/phương tiện-ngày','DVT2940');
Insert into dmdvt (dvt,madvt) values (N'đồng/3 ngày đầu tiên','DVT2941');
Insert into dmdvt (dvt,madvt) values (N'đồng/người/lượt','DVT2942');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần vào hoặc ra','DVT2943');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần đóng hoặc mở hầm','DVT2944');
Insert into dmdvt (dvt,madvt) values (N'đồng/cont','DVT2945');
Insert into dmdvt (dvt,madvt) values (N'đồng/giờ/cont','DVT2946');
Insert into dmdvt (dvt,madvt) values (N'đồng/chiếc-ngày','DVT2947');
Insert into dmdvt (dvt,madvt) values (N'đồng/giờ-người','DVT2948');
Insert into dmdvt (dvt,madvt) values (N'đồng/ca-người','DVT2949');
Insert into dmdvt (dvt,madvt) values (N'đồng/giờ','DVT2950');
Insert into dmdvt (dvt,madvt) values (N'đồng/chiếc/ngày','DVT2951');
Insert into dmdvt (dvt,madvt) values (N'đồng/xe','DVT2952');
Insert into dmdvt (dvt,madvt) values (N'RT','DVT2953');
Insert into dmdvt (dvt,madvt) values (N'1 container hàng khô 20 feet','DVT2954');
Insert into dmdvt (dvt,madvt) values (N'1 container hàng khô 40 feet','DVT2955');
Insert into dmdvt (dvt,madvt) values (N'1 container hàng khô 45 feet','DVT2956');
Insert into dmdvt (dvt,madvt) values (N'1 container hàng lạnh 20 feet','DVT2957');
Insert into dmdvt (dvt,madvt) values (N'1 container hàng lạnh 40 feet','DVT2958');
Insert into dmdvt (dvt,madvt) values (N'1 container rỗng khô 20 feet','DVT2959');
Insert into dmdvt (dvt,madvt) values (N'1 container rỗng khô 40 feet','DVT2960');
Insert into dmdvt (dvt,madvt) values (N'1 container rỗng khô 45 feet','DVT2961');
Insert into dmdvt (dvt,madvt) values (N'1 container rỗng lạnh 20 feet','DVT2962');
Insert into dmdvt (dvt,madvt) values (N'1 container rỗng lạnh 40 feet','DVT2963');
Insert into dmdvt (dvt,madvt) values (N'Tấn quy đổi (RT)','DVT2964');
Insert into dmdvt (dvt,madvt) values (N'Đồng/cont-giờ','DVT2965');
Insert into dmdvt (dvt,madvt) values (N'Tuýp','DVT2966');
Insert into dmdvt (dvt,madvt) values (N'Xô','DVT2967');
Insert into dmdvt (dvt,madvt) values (N'Kế hoạch vốn giao trong năm','DVT3102');
Insert into dmdvt (dvt,madvt) values (N'đ/ lít','DVT3122');
Insert into dmdvt (dvt,madvt) values (N'FEET','DVT3911');
Insert into dmdvt (dvt,madvt) values (N'1000 BAO','DVT3914');
Insert into dmdvt (dvt,madvt) values (N'OUNCE','DVT3917');
Insert into dmdvt (dvt,madvt) values (N'ROLL','DVT3918');
Insert into dmdvt (dvt,madvt) values (N'đ/người/chuyến','DVT3931');
Insert into dmdvt (dvt,madvt) values (N'đ/phòng/ngày đêm','DVT3932');
Insert into dmdvt (dvt,madvt) values (N'SEK','DVT3951');
Insert into dmdvt (dvt,madvt) values (N'CM','DVT3952');
Insert into dmdvt (dvt,madvt) values (N'đ/lit','DVT3971');
Insert into dmdvt (dvt,madvt) values (N'LO (NHIEU CAI)','DVT4011');
Insert into dmdvt (dvt,madvt) values (N'CU','DVT4012');
Insert into dmdvt (dvt,madvt) values (N'BICH','DVT4017');
Insert into dmdvt (dvt,madvt) values (N'KIT','DVT4031');
Insert into dmdvt (dvt,madvt) values (N'DON VI','DVT4032');
Insert into dmdvt (dvt,madvt) values (N'ONG','DVT4033');
Insert into dmdvt (dvt,madvt) values (N'YARDS','DVT4034');
Insert into dmdvt (dvt,madvt) values (N'VIEN','DVT4035');
Insert into dmdvt (dvt,madvt) values (N'CAI','DVT4036');
Insert into dmdvt (dvt,madvt) values (N'BO','DVT4037');
Insert into dmdvt (dvt,madvt) values (N'CAY','DVT4038');
Insert into dmdvt (dvt,madvt) values (N'DOI','DVT4039');
Insert into dmdvt (dvt,madvt) values (N'MET VUONG','DVT4040');
Insert into dmdvt (dvt,madvt) values (N'SAN PHAM','DVT4041');
Insert into dmdvt (dvt,madvt) values (N'TAN','DVT4042');
Insert into dmdvt (dvt,madvt) values (N'VI','DVT4043');
Insert into dmdvt (dvt,madvt) values (N'CANH','DVT4044');
Insert into dmdvt (dvt,madvt) values (N'MET','DVT4045');
Insert into dmdvt (dvt,madvt) values (N'GOI','DVT4046');
Insert into dmdvt (dvt,madvt) values (N'TUI','DVT4047');
Insert into dmdvt (dvt,madvt) values (N'LIT','DVT4048');
Insert into dmdvt (dvt,madvt) values (N'LIEU','DVT4049');
Insert into dmdvt (dvt,madvt) values (N'HE THONG','DVT4050');
Insert into dmdvt (dvt,madvt) values (N'THUNG','DVT4051');
Insert into dmdvt (dvt,madvt) values (N'TAM','DVT4052');
Insert into dmdvt (dvt,madvt) values (N'SOI','DVT4053');
Insert into dmdvt (dvt,madvt) values (N'CUC','DVT4054');
Insert into dmdvt (dvt,madvt) values (N'TO','DVT4055');
Insert into dmdvt (dvt,madvt) values (N'GALONG RUOU','DVT4056');
Insert into dmdvt (dvt,madvt) values (N'TROY OUNCE','DVT4071');
Insert into dmdvt (dvt,madvt) values (N'QUA','DVT4072');
Insert into dmdvt (dvt,madvt) values (N'MILILIT','DVT4073');
Insert into dmdvt (dvt,madvt) values (N'BRL','DVT4091');
Insert into dmdvt (dvt,madvt) values (N'TUT','DVT4092');
Insert into dmdvt (dvt,madvt) values (N'TA (100KG)','DVT4093');
Insert into dmdvt (dvt,madvt) values (N'BANG','DVT4094');
Insert into dmdvt (dvt,madvt) values (N'đ/lượt 60 phút','DVT4111');
Insert into dmdvt (dvt,madvt) values (N'đ/gói 1g','DVT4112');
Insert into dmdvt (dvt,madvt) values (N'đ/gói 0,5g','DVT4113');
Insert into dmdvt (dvt,madvt) values (N'đ/100g','DVT4114');
Insert into dmdvt (dvt,madvt) values (N'đ/gói 50g','DVT4115');
Insert into dmdvt (dvt,madvt) values (N'đ/gói 100g','DVT4116');
Insert into dmdvt (dvt,madvt) values (N'đ/gói 20g','DVT4117');
Insert into dmdvt (dvt,madvt) values (N'đ/25 liều/lọ','DVT4118');
Insert into dmdvt (dvt,madvt) values (N'đ/10 liều/lọ','DVT4119');
Insert into dmdvt (dvt,madvt) values (N'đ/200 liều/lọ','DVT4120');
Insert into dmdvt (dvt,madvt) values (N'đ/250 liều/lọ','DVT4121');
Insert into dmdvt (dvt,madvt) values (N'PAL','DVT4131');
Insert into dmdvt (dvt,madvt) values (N'NGHIN','DVT4132');
Insert into dmdvt (dvt,madvt) values (N'1000 VIEN','DVT4133');
Insert into dmdvt (dvt,madvt) values (N'GBP','DVT4151');
Insert into dmdvt (dvt,madvt) values (N'7700','DVT4171');
Insert into dmdvt (dvt,madvt) values (N'13408','DVT4172');
Insert into dmdvt (dvt,madvt) values (N'57920','DVT4173');
Insert into dmdvt (dvt,madvt) values (N'đông','DVT4191');
Insert into dmdvt (dvt,madvt) values (N'dồng','DVT4192');
Insert into dmdvt (dvt,madvt) values (N'kg .','DVT4193');
Insert into dmdvt (dvt,madvt) values (N's','DVT4211');
Insert into dmdvt (dvt,madvt) values (N'25','DVT4212');
Insert into dmdvt (dvt,madvt) values (N'd/kg','DVT4231');
Insert into dmdvt (dvt,madvt) values (N'_kg','DVT4251');
Insert into dmdvt (dvt,madvt) values (N'. kg','DVT4252');
Insert into dmdvt (dvt,madvt) values (N'kg _','DVT4253');
Insert into dmdvt (dvt,madvt) values (N'- kg','DVT4254');
Insert into dmdvt (dvt,madvt) values (N'vnd/kg','DVT4255');
Insert into dmdvt (dvt,madvt) values (N'Đ/Kgl','DVT4256');
Insert into dmdvt (dvt,madvt) values (N'Đ/ỈCg','DVT4257');
Insert into dmdvt (dvt,madvt) values (N'25kg','DVT4258');
Insert into dmdvt (dvt,madvt) values (N'40kg','DVT4259');
Insert into dmdvt (dvt,madvt) values (N'5kg','DVT4260');
Insert into dmdvt (dvt,madvt) values (N'25k¡','DVT4261');
Insert into dmdvt (dvt,madvt) values (N'.25 kg','DVT4262');
Insert into dmdvt (dvt,madvt) values (N'25Kgs','DVT4263');
Insert into dmdvt (dvt,madvt) values (N'Kgs','DVT4264');
Insert into dmdvt (dvt,madvt) values (N'K-g','DVT4271');
Insert into dmdvt (dvt,madvt) values (N'đ/tẩn','DVT4272');
Insert into dmdvt (dvt,madvt) values (N'lượng KG','DVT4291');
Insert into dmdvt (dvt,madvt) values (N'CAI','DVT4292');
Insert into dmdvt (dvt,madvt) values (N'KCi','DVT4293');
Insert into dmdvt (dvt,madvt) values (N'ICG','DVT4294');
Insert into dmdvt (dvt,madvt) values (N'kẹ','DVT4311');
Insert into dmdvt (dvt,madvt) values (N'I/át vuông','DVT4331');
Insert into dmdvt (dvt,madvt) values (N'QUYEN','DVT4332');
Insert into dmdvt (dvt,madvt) values (N'Ringgit Malaysia','DVT4333');
Insert into dmdvt (dvt,madvt) values (N'CUON','DVT4334');
Insert into dmdvt (dvt,madvt) values (N'Ruble Nga','DVT4335');
Insert into dmdvt (dvt,madvt) values (N'AUD','DVT4351');
Insert into dmdvt (dvt,madvt) values (N'CNY','DVT4371');
Insert into dmdvt (dvt,madvt) values (N'Nghìn đồng/m2','DVT4391');
Insert into dmdvt (dvt,madvt) values (N'đồng/kWh','DVT4392');
Insert into dmdvt (dvt,madvt) values (N'MW','DVT4394');
Insert into dmdvt (dvt,madvt) values (N'kg/kwh','DVT4395');
Insert into dmdvt (dvt,madvt) values (N'kcal/kg','DVT4396');
Insert into dmdvt (dvt,madvt) values (N'Đồng/tấn','DVT4397');
Insert into dmdvt (dvt,madvt) values (N'đồng/USD','DVT4398');
Insert into dmdvt (dvt,madvt) values (N'Thiết bị','DVT4399');
Insert into dmdvt (dvt,madvt) values (N'Chai','DVT4400');
Insert into dmdvt (dvt,madvt) values (N'm','DVT4401');
Insert into dmdvt (dvt,madvt) values (N'Mép dài cáp','DVT4402');
Insert into dmdvt (dvt,madvt) values (N'USD/tấn','DVT4411');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/tấn','DVT4412');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/lượt xe','DVT4413');
Insert into dmdvt (dvt,madvt) values (N'USD/khách/giờ','DVT4414');
Insert into dmdvt (dvt,madvt) values (N'USD/khách/ngày','DVT4415');
Insert into dmdvt (dvt,madvt) values (N'USD/hành khách','DVT4416');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/hành khách','DVT4417');
Insert into dmdvt (dvt,madvt) values (N'USD/lượt hạ cánh hoặc cất cánh','DVT4418');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/chuyến bay','DVT4419');
Insert into dmdvt (dvt,madvt) values (N'USD/chuyến','DVT4420');
Insert into dmdvt (dvt,madvt) values (N'USD/lần','DVT4421');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/lần','DVT4422');
Insert into dmdvt (dvt,madvt) values (N'Đồng/GT/HL','DVT4431');
Insert into dmdvt (dvt,madvt) values (N'USD/GT/HL','DVT4432');
Insert into dmdvt (dvt,madvt) values (N'Đồng/GT/giờ','DVT4433');
Insert into dmdvt (dvt,madvt) values (N'Đồng/m-giờ','DVT4434');
Insert into dmdvt (dvt,madvt) values (N'USD/GT/giờ','DVT4435');
Insert into dmdvt (dvt,madvt) values (N'USD/m-giờ','DVT4436');
Insert into dmdvt (dvt,madvt) values (N'USD/cont','DVT4437');
Insert into dmdvt (dvt,madvt) values (N'USD/chiếc','DVT4438');
Insert into dmdvt (dvt,madvt) values (N'USD/người','DVT4439');
Insert into dmdvt (dvt,madvt) values (N'USD/giờ','DVT4451');
Insert into dmdvt (dvt,madvt) values (N'đồng/vé/lượt','DVT4452');
Insert into dmdvt (dvt,madvt) values (N'đồng/km','DVT4453');
Insert into dmdvt (dvt,madvt) values (N'đồng/lượt','DVT4454');
Insert into dmdvt (dvt,madvt) values (N'đồng/tháng','DVT4455');
Insert into dmdvt (dvt,madvt) values (N'đồng/chuyến','DVT4456');
Insert into dmdvt (dvt,madvt) values (N'1.000 đồng/ha/vụ','DVT4457');
Insert into dmdvt (dvt,madvt) values (N'đồng/m3','DVT4471');
Insert into dmdvt (dvt,madvt) values (N'đồng/m2 mặt thoáng/năm','DVT4472');
Insert into dmdvt (dvt,madvt) values (N'đồng/xét nghiệm','DVT4491');
Insert into dmdvt (dvt,madvt) values (N'đồng/xét nghiệm/chỉ tiêu','DVT4492');
Insert into dmdvt (dvt,madvt) values (N'đồng/mẫu/chỉ tiêu','DVT4493');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần nuôi cấy','DVT4494');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần xét nghiệm','DVT4495');
Insert into dmdvt (dvt,madvt) values (N'đồng/hồ sơ','DVT4496');
Insert into dmdvt (dvt,madvt) values (N'đồng/người','DVT4497');
Insert into dmdvt (dvt,madvt) values (N'đồng/người /chuyên khoa','DVT4498');
Insert into dmdvt (dvt,madvt) values (N'đồng/phim','DVT4499');
Insert into dmdvt (dvt,madvt) values (N'đồng/chuyên gia/ca','DVT4500');
Insert into dmdvt (dvt,madvt) values (N'đồng/thử nghiệm','DVT4501');
Insert into dmdvt (dvt,madvt) values (N'đồng/bảng kiểm','DVT4502');
Insert into dmdvt (dvt,madvt) values (N'đồng/khớp/tư thế','DVT4503');
Insert into dmdvt (dvt,madvt) values (N'đồng/bảng','DVT4504');
Insert into dmdvt (dvt,madvt) values (N'đồng/trường','DVT4505');
Insert into dmdvt (dvt,madvt) values (N'đồng/lớp','DVT4506');
Insert into dmdvt (dvt,madvt) values (N'đồng/lớp','DVT4507');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần kiểm định','DVT4508');
Insert into dmdvt (dvt,madvt) values (N'Đồng/lô/lần nhập khẩu','DVT4509');
Insert into dmdvt (dvt,madvt) values (N'đồng/mẫu tiêu bản','DVT4510');
Insert into dmdvt (dvt,madvt) values (N'đồng/mẫu vật','DVT4511');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần điều tra','DVT4512');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần phân lập','DVT4513');
Insert into dmdvt (dvt,madvt) values (N'đồng/1 lần tiêm','DVT4514');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần kiểm tra','DVT4515');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần mổ','DVT4516');
Insert into dmdvt (dvt,madvt) values (N'đồng/mẫu xét nghiệm','DVT4517');
Insert into dmdvt (dvt,madvt) values (N'Đồng/GT','DVT4531');
Insert into dmdvt (dvt,madvt) values (N'đồng/mẫu','DVT4532');
Insert into dmdvt (dvt,madvt) values (N'USD/m3 khoang tàu','DVT4533');
Insert into dmdvt (dvt,madvt) values (N'USD/tàu bay','DVT4534');
Insert into dmdvt (dvt,madvt) values (N'đồng/Phương tiện','DVT4535');
Insert into dmdvt (dvt,madvt) values (N'đồng/toa','DVT4536');
Insert into dmdvt (dvt,madvt) values (N'USD/m3kho hàng','DVT4537');
Insert into dmdvt (dvt,madvt) values (N'USD/container','DVT4538');
Insert into dmdvt (dvt,madvt) values (N'USD/tàu','DVT4539');
Insert into dmdvt (dvt,madvt) values (N'USD/m2diện tích khử trùng','DVT4540');
Insert into dmdvt (dvt,madvt) values (N'USD/lần kiểm tra','DVT4541');
Insert into dmdvt (dvt,madvt) values (N'USD/lần xử lý','DVT4542');
Insert into dmdvt (dvt,madvt) values (N'USD/lần kiểm tra /kiện, lô mẫu, sản phẩm, mô, bộ phận','DVT4543');
Insert into dmdvt (dvt,madvt) values (N'USD/ mẫu','DVT4544');
Insert into dmdvt (dvt,madvt) values (N'USD/lần/tàu','DVT4545');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần/xe','DVT4546');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần/phương tiện','DVT4547');
Insert into dmdvt (dvt,madvt) values (N'đồng/km2/năm','DVT4548');
Insert into dmdvt (dvt,madvt) values (N'đ/ lần/ hải đăng','DVT4551');
Insert into dmdvt (dvt,madvt) values (N'đ/ lần/ km','DVT4552');
Insert into dmdvt (dvt,madvt) values (N'Liều','DVT4571');
Insert into dmdvt (dvt,madvt) values (N'USD/Can','DVT4591');
Insert into dmdvt (dvt,madvt) values (N'Đồng/Gói','DVT4592');
Insert into dmdvt (dvt,madvt) values (N'Hũ','DVT4593');
Insert into dmdvt (dvt,madvt) values (N'Hộp (6 viên)','DVT4594');
Insert into dmdvt (dvt,madvt) values (N'Hộp (5 lọ)','DVT4595');
Insert into dmdvt (dvt,madvt) values (N'Hộp (60 viên)','DVT4596');
Insert into dmdvt (dvt,madvt) values (N'Hộp (30 viên)','DVT4597');
Insert into dmdvt (dvt,madvt) values (N'Hộp (10 viên)','DVT4598');
Insert into dmdvt (dvt,madvt) values (N'Hộp (3 viên)','DVT4599');
Insert into dmdvt (dvt,madvt) values (N'Đồng/Can','DVT4611');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/Gói','DVT4612');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/Can','DVT4613');
Insert into dmdvt (dvt,madvt) values (N'VNĐ/Chai','DVT4614');
Insert into dmdvt (dvt,madvt) values (N'Am pun','DVT4615');
Insert into dmdvt (dvt,madvt) values (N'Hộp (3 ống)','DVT4616');
Insert into dmdvt (dvt,madvt) values (N'Hộp 30 viên','DVT4617');
Insert into dmdvt (dvt,madvt) values (N'Hộp 24 viên','DVT4618');
Insert into dmdvt (dvt,madvt) values (N'Hộp 10 viên','DVT4619');
Insert into dmdvt (dvt,madvt) values (N'Vỏ','DVT4631');
Insert into dmdvt (dvt,madvt) values (N'Đ/T','DVT4632');
Insert into dmdvt (dvt,madvt) values (N'USD/cont','DVT4633');
Insert into dmdvt (dvt,madvt) values (N'Đồng/lượt cập hoặc rời','DVT4651');
Insert into dmdvt (dvt,madvt) values (N'USD/lượt cập hoặc rời','DVT4652');
Insert into dmdvt (dvt,madvt) values (N'đồng/lần/tàu','DVT4664');
Insert into dmdvt (dvt,madvt) values (N'đồng/m2 sàn','DVT4665');

*/
